language: java
jdk:
  - oraclejdk8
sudo: true
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y ntp
  - sudo service ntp start
script:
  - ./gradlew check
  - ./gradlew publishToMavenLocal
  - cd examples/order && ./gradlew check
after_success:
  - ./gradlew -Psnapshot=true :eventsourcing-core:bintrayUpload :eventsourcing-layout:bintrayUpload :eventsourcing-hlc:bintrayUpload :eventsourcing-h2:bintrayUpload
env:
  global:
  - secure: MilncdIQ2jjsSd8r31lNjoeUdNaeCs5mOgKhidUyQmyDmqOKru/Cj7z/UqeAIZswG/Pj+PO+RW5UbAl28OAbVv1i/4jrHL8UhHhIvVxNPMFle22BcssLzIWcuRNwS8fq0+K6i/xMZUDUYoGuvNMMf7r3JTuX8W5iNUQmlvBX/i3LZnaX2yQYnP8o/MtWrN6LNCFGGVxXukLII4ZKHcvefkcwEz2cdmNEsooKPJyrIAkvURyNYCRqnheJZ/rq+AUcSUN3V0OHaVULO05HJ0Gmfzw8OqswZC8QcyEFZ0QdjoPVKCau5l/UlJs2q9QA9xsdZkPrUJqRjY8Ve0ZCwHZgiuvCiBVdzdaJeXLVYScFMaTr11t2XHT9AIoX+4KohSoRJpuJm21CeIn0D5dG5KaHAl1A7MDccKHxkvGt9rDoDXUuFSqxjuoRy2KOl3JEWUtAHpt7GVRwYjzISoyV+ws59J1tNrFGaAGKcBLFtozQbG8Xk5TibVcNQg7KfF9kU3mfb/TNCnbd7/XfZdObFjr7GZ89qkYztAiSz2MRa2zXseL1jjvYqNvXEc8prKnfP0yktE2Ld1wv50OBGExQUuQcmgO9WqcwPuR6VhgJwm500vi6e6H7rQMQqYv5W9pXrbT5RakK6nHyowRpy8a24MwuudgseJf8ZlScCttSatAvwGg=
  - secure: dDOZpAlFu4P1NhhiGQkDNY9sk5KzXkBqnuEGUFKjamsTKYUWjMMbrfZI/DJ2kDWv5ONuDHinUCLRxJEVYEX9qxihv+6voYDJhk1IMqkPAZ33FV6fnTc0rCsuMZtp8k9tQrJFYXsldr+DpAf8sQ+zpJoYDvhnfQ4kFpsxvoJrvohfwRxICEncYESyADmSBz4s7/G8GpPDn7/rRQ6q+Diua1kpNA7Tmwd2H3raEVN5h9rBuXQ+1Elky6uWieJY1Z2mJK6VRjw6NoteRFcPl2zjOctqBEHC3zfPi+8WlQ1PHxm+7IN0CB9MZ+2Hc3mP8yqIuF7BWpKKtCUYtTdVEaF2MqCFpHBdwuSO0XnI9g8yEDHz9AjwHmJrq2R27wEeBdfmqDiNJHvrdDzr4WFxDk5zwS+NCh/pmrnAVR6QhglAg/omqPVq5XQmYU3WSwQPcQmjcGq3sP0Kmt8Bjnt3VSN0HeCPnlOJGeRI4yzbk2FyYxdsX7xMdctN517Wm5B8hA/H97lqzhibNGTUVCX36al/h3CswAdxRV0qX2UxWNDHugm5MQoP43K/buJzJ2XpcCSqhGEqSVLl1n/nbFyB2/Bf89geu3XZTB+agc6xX5B/WYgNaCZ11G3CNBqpMAOmATojwABi73JQrIQ1akLsB6DH6jezDW4hIYexHF8evUNQudA=
